In [113]:
#Importing the necessary libraries

%pylab inline 
import numpy as np


Populating the interactive namespace from numpy and matplotlib


In [ ]:
#PART I
#Initializing the array

y_hat = np.linspace(-1., 1., 20)  #(From -1 to 1, with 20 spaces)
y     = np.linspace( 0., 1., 20)  #(From  0 to 1, with 20 spaces)

In [115]:
#Prints the two initialized array

print(y_hat)
print(y)

[-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [116]:
#Displays the shape of both array

print('shape of y_hat array :', y_hat.shape)
print('shape of y array :', y.shape)

#Displays the dimensions of both array

print('Dimension of y_hat array: ' , y_hat.ndim)
print('Dimension of y array: ' , y.ndim)

shape of y_hat array : (20,)
shape of y array : (20,)
Dimension of y_hat array:  1
Dimension of y array:  1


In [ ]:
#This function computes the Mean Squared Error

def mean_squared_error(y_bar, y):

   diff = y - y_bar
   differences_squared = diff ** 2
   mean_diff = differences_squared.mean()
   
   return mean_diff

print("The Mean Squared Error is: ", mean_squared_error(y_hat,y))

The Mean Squared Error is:  0.3421052631578948


In [117]:
#This function computes the Mean Squared Logarithmic Error


def mean_squared_logarithmic(y_bar,y):
  summation = 0  
  n = len(y) 
  for i in range (0,n): 
    difference = y[i] - y_bar[i]  
    squared_difference = difference**2  
    summation = summation + squared_difference  
  MSE = summation/n  
  return summation

print("The Mean Square Logarithmic Error is: " , mean_squared_logarithmic(y_hat,y))

The Mean Square Logarithmic Error is:  6.842105263157895


In [ ]:
#This function computes the Mean Absolute Error

def mean_absolute_error(y_bar, y):
    diff = y - y_bar
    absolute_diff = np.absolute(diff)
    mean_difference = absolute_diff.mean()
    return mean_difference

print("The Mean absolute Error is: ", mean_absolute_error(y_hat,y))

The Mean absolute Error is:  0.4999999999999999


In [118]:
#This function computes the Mean Absolute Percentage Error

def mean_absolute_percentage_error(y_bar, y): 
    y_bar, pred = np.array(y_bar), np.array(y)
    return np.mean(np.abs((y_bar - y) / y_bar)) 

print("The mean absolute percentage Error is: ", mean_absolute_percentage_error(y_hat,y))

The mean absolute percentage Error is:  2.0265927536515775


In [123]:
#PART II

#Creates a 1D array, with content 1 to 16
M = np.arange(1,17)

#Reshape the 1D array to 4x4 
N = M.reshape(4, 4)

print("The new dimension of the array M: \n", n)
print("Print the 2nd row of N: \n", N[1:2])

The new dimension of the array M: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Print the 2nd row of N: 
 [[5 6 7 8]]


In [124]:
#Prints the minimum value per column

MinVal_perColumns = np.amin(N, axis=0)
print("The minimum value per columns are: ", MinVal_perColumns)

The minimum value per columns are:  [1 2 3 4]


In [125]:
#Prints the average of matrix N

average_of_matrix = np.average(N)

print("The average of the matrix N is :",average_of_matrix)

The average of the matrix N is : 8.5


In [109]:
#Creates a vector

V = np.array([1, 1, 1, 1])
print("The content of vector V are: ", V)

The content of vector V are:  [1 1 1 1]


In [126]:
#Print the dot product of N and V

dot_product = np.dot(N,V)
print("The dot product of N and V are: ", dot_product)

The dot product of N and V are:  [10 26 42 58]
